### ISSUE TITLE
Get the students teammates

### ISSUE THREAD

**Issue by shikharchaure** [cse522summer2019/project#19]
Get the students team members (id and full name) from the database and return to the client

**Comment by apellechia** [comment]
Task Test:

1. Makes sure you are a student in the database
2. Add yourself to a team of students in the database. Create a team in team or use one if already there. Then in StudentTeams add yourself and other students to the team by setting students from Logininfo to a team from Teams.   
3. Login to the system
4. Go to: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/getEvaluation.php
5. You should see a json object containing an object with yourself and an object that has an array of your teammates on the screen.

**Comment by apellechia** [comment]
Task Test: (not logged in)

1. Makes sure you are a student in the database
2. Add yourself to a team of students in the database. Create a team in team or use one if already there. Then in StudentTeams add yourself and other students to the team by setting students from Logininfo to a team from Teams.
3. Go to: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/getEvaluation.php
4. Since you are not logged in, you should see a string {"error": false}
