### ISSUE TITLE
Populate saved scores for the revision 

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#23]
Populate the returned scores on the evaluation page. These scores are the ones that have been stored from a previous review.

**Comment by shikharchaure** [comment]
Task Test :
If you have already filled evaluations and need to update any values
1. Go to login page - https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/login.
Enter email id and click on submit button. You will receive a unique confirmation code on your email Id.
2.You will be redirected to a page which asks for Confirmation Code.
3. Enter confirmation code, you will be redirected to the evaluation page.
4. Since you have already filled evaluations once, you will see your previous selected evaluations.
5. Modify your evaluations by selecting from drop down and clicking on the "Submit Evaluations" buttons you should see new page which displays "Thank you for your reviews".

**Comment by shikharchaure** [comment]
Task Test :
1.  Go to: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/EvaluationPage.html
2.  Since you are not signed in you will be redirected to the confirmation page.
